name: Validate XML Examples Against Schemas

on:
  push:
    branches:
      - main
    paths:
      - "schemas/**.xsd"
      - "examples/**.xml"
  pull_request:
    branches:
      - main
    paths:
      - "schemas/**.xsd"
      - "examples/**.xml"
jobs:
  validate-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pathlib lxml

      - name: Validate XML Payloads against Schemas
        run: python scripts/validate.py
